# Generated by Django 5.1.5 on 2025-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvelmodel',
            old_name='heroic_name',
            new_name='last_name',
        ),
    ]
