# Generated by Django 5.1.5 on 2025-02-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_heroic_name_marvelmodel_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarvelModel',
            new_name='CollegeAdmission',
        ),
    ]
