# Generated by Django 5.1.5 on 2025-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_marvelmodel_collegeadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarvelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heroic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CollegeAdmission',
        ),
    ]
